# 图片上传配置（VitePress public标准路径）
media:
  input: public/posts
  output: /posts

# 内容集合
content:
  # 1. BA主题博客文章（核心）
  - name: posts
    label: 博客文章
    type: collection
    path: /posts
    filename: "{year}-{month}-{day}-{slug}.md"
    view:
      fields: [title, date, cover, tags, pinned]
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true
        default: ""
      - name: date
        label: 发布日期
        type: date
        required: true
      - name: cover
        label: 封面图
        type: image
        default: ""
      - name: tags
        label: 标签(用,分隔)
        type: list
        widget: string
        default: []
      - name: pinned
        label: 置顶文章(true和false)
        type: switch
        default: "false"
      - name: head
        label: SEO配置
        type: object
        fields:
          - name: metaDesc
            label: 页面描述(description)
            type: string
            default: ""
          - name: metaKeywords
            label: 页面关键词(keywords)
            type: string
            default: ""
      - name: body
        label: 正文内容
        type: rich-text
        formats:
          - markdown
        default: "\n\n---\n"